export const quotes: string[] = [
    'Believe you can and you\'re halfway there. -Theodore Roosevelt',
    'You are never too old to set another goal or to dream a new dream. -C.S. Lewis',
    'You don\'t have to be great to start, but you have to start to be great. -Zig Ziglar',
    'Happiness is not something ready made. It comes from your own actions. -Dalai Lama',
    'The only way to do great work is to love what you do. -Steve Jobs',
    'Success is not final, failure is not fatal: it is the courage to continue that counts. -Winston Churchill',
    'You are the only one who can limit your greatness. -Unknown',
    'You are the master of your destiny. You can influence, direct and control your own environment. -Napoleon Hill',
    'I can\'t change the direction of the wind, but I can adjust my sails to always reach my destination. -Jimmy Dean',
    'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. -Christian D. Larson',
    'It does not matter how slowly you go as long as you do not stop. -Confucius',
    'Success is stumbling from failure to failure with no loss of enthusiasm. -Winston Churchill',
    'The best way to predict the future is to create it. -Peter Drucker',
    'I have not failed. I\'ve just found 10,000 ways that won\'t work. -Thomas Edison',
    'If you want to live a happy life, tie it to a goal, not to people or things. -Albert Einstein',
    'Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this. -Chantal Sutherland',
    'The only time you should look back is to see how far you\'ve come. -Unknown',
    'The future belongs to those who believe in the beauty of their dreams. -Eleanor Roosevelt',
    'Don\'t let yesterday take up too much of today. -Will Rogers',
    'The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela',
    'If you don\'t stand for something you will fall for anything. -Malcolm X',
    'You can\'t go back and change the beginning, but you can start where you are and change the ending. -C.S. Lewis',
    'Believe in yourself, push your limits, and do whatever it takes to conquer your goals. -Unknown',
    'No matter what people tell you, words and ideas can change the world. -Robin Williams',
    'If you look at what you have in life, you\'ll always have more. If you look at what you don\'t have in life, you\'ll never have enough. -Oprah Winfrey',
    'You are not a drop in the ocean. You are the entire ocean in a drop. -Rumi',
    'The greatest wealth is to live content with little. -Plato',
    'Be kind, for everyone you meet is fighting a battle you know nothing about. -Wendy Mass',
    'If you want to lift yourself up, lift up someone else. -Booker T. Washington',
    'The only person you are destined to become is the person you decide to be. -Ralph Waldo Emerson',
    'The only limit to our realization of tomorrow will be our doubts of today. -Franklin D. Roosevelt',
    'The best revenge is massive success. -Frank Sinatra',
    'The only way to do great work is to love what you do. -Steve Jobs',
    'The best way to predict the future is to create it. -Peter Drucker',
    'The only person you are destined to become is the person you decide to be. -Ralph Waldo Emerson',
];
